In [2]:
movie_comment = '/Users/mqgao/Workspace/Lecture/datasource/movie_comments.csv'  # Notice: The movie comment.csv in source code is located in https://github.com/Artificial-Intelligence-for-NLP/datasource

In [3]:
import pandas as pd

In [4]:
content = pd.read_csv(movie_comment)

/anaconda3/envs/fastprint/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3018: DtypeWarning: Columns (0,4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [7]:
content[-10:]

id                                       link  \
261487  260140  https://movie.douban.com/subject/1441763/   
261488  260141  https://movie.douban.com/subject/1441763/   
261489  260142  https://movie.douban.com/subject/1441763/   
261490  260143  https://movie.douban.com/subject/1441763/   
261491  260144  https://movie.douban.com/subject/1441763/   
261492  260145  https://movie.douban.com/subject/1441763/   
261493  260146  https://movie.douban.com/subject/1441763/   
261494  260147  https://movie.douban.com/subject/1441763/   
261495  260148  https://movie.douban.com/subject/1441763/   
261496  260149  https://movie.douban.com/subject/1441763/   

                             name  \
261487  不羁美少年 À cause d'un garçon   
261488  不羁美少年 À cause d'un garçon   
261489  不羁美少年 À cause d'un garçon   
261490  不羁美少年 À cause d'un garçon   
261491  不羁美少年 À cause d'un garçon   
261492  不羁美少年 À cause d'un garçon   
261493  不羁美少年 À cause d'un garçon   
261494  不羁美少年 À cause d'un garçon   
261495  不羁美少年 À cause d'un garçon   
261496  不羁美少年 À cause d'un garçon   

                                              comment star  
261487                                         轻松喜剧电影    4  
261488                                 温暖的剧情,温暖的结局...    3  
261489           主角们都很好看 又是一个碧悲情的小女主角\r\n又是一段关于十七岁的故事    5  
261490                            一切都是爲了顏！！！= =||||||    3  
261491   大概看了\r\n总的来说还是不错 其实内心是十分期待男主和他的好友发生点什么的 哎。。。    3  
261492                 内容只能说一般。。女性角色怎么都这么悲催啊！！不过男猪脚很帅    3  
261493                       翘了三天班就窝在家里看小基片惹（手动拜拜.gif    3  
261494  我喜欢女主角，希腊雕塑一般的面庞与身体。（在一部同志题材的电影中迷恋女主角好像很不应该吧）    2  
261495                                     冲着颜值还可以看下去    3  
261496             除了主人公都不帅，女主挺漂亮之外……唯一的感觉就是他男朋友真让人恶心    3

In [8]:
all_comments = content['comment'].tolist()

In [10]:
all_comments[-10:]

['轻松喜剧电影',
 '温暖的剧情,温暖的结局...',
 '主角们都很好看 又是一个碧悲情的小女主角\r\n又是一段关于十七岁的故事',
 '一切都是爲了顏！！！= =||||||',
 '大概看了\r\n总的来说还是不错 其实内心是十分期待男主和他的好友发生点什么的 哎。。。',
 '内容只能说一般。。女性角色怎么都这么悲催啊！！不过男猪脚很帅',
 '翘了三天班就窝在家里看小基片惹（手动拜拜.gif',
 '我喜欢女主角，希腊雕塑一般的面庞与身体。（在一部同志题材的电影中迷恋女主角好像很不应该吧）',
 '冲着颜值还可以看下去',
 '除了主人公都不帅，女主挺漂亮之外……唯一的感觉就是他男朋友真让人恶心']

In [11]:
import jieba

In [12]:
def cut(string): return list(jieba.cut(string))

In [16]:
def generate_test():
#    result = []
    
    for i in range(10000000000000000000000000000000000000000000000):
        yield i ** 2
#        result.append(i**2)
        
#    return result

In [19]:
L = generate_test(10)
for i in L:
    print('\t', i)

	 0
	 1
	 4
	 9
	 16
	 25
	 36
	 49
	 64
	 81


In [20]:
for i in L:
    print('\t', i)

In [15]:
all_comments = [' '.join(cut(s)) for s in all_comments if isinstance(s, str)]

In [32]:
import random

In [34]:
samples = random.sample(all_comments, 10000)

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [41]:
vectorizer = TfidfVectorizer(max_features=30000)

In [42]:
X = vectorizer.fit_transform(samples)

In [71]:
id_word = {i: w for w, i in vectorizer.vocabulary_.items()}

In [77]:
import numpy as np

In [81]:
samples[1]

'没笑点 ， 顶多 是 有点 喜感 ， 这仅 有 的 喜感 也 来自 于 故事 的 荒谬'

In [82]:
np.where(X[1].toarray()[0])

(array([ 7589, 13286, 14334, 14658, 15752, 20562, 22406, 24086]),)

In [84]:
X[1].toarray()[0][7589]

0.5870349487694185

In [83]:
id_word[7589]

'喜感'

In [69]:
list(X[0].toarray()[0])

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [43]:
X.shape

(10000, 24765)

In [44]:
from sklearn.cluster import KMeans

In [85]:
kmeans = KMeans(n_clusters=30, random_state=0).fit(X)

In [86]:
kmeans.labels_

array([26, 14, 26, ...,  7, 26, 14], dtype=int32)

In [87]:
all_labels = kmeans.labels_.tolist()

In [88]:
from collections import defaultdict

In [89]:
lables_with_comment = defaultdict(list)

In [90]:
for i, label in enumerate(all_labels):
    lables_with_comment[label].append(samples[i])

In [93]:
lables_with_comment[10]

['真是 好看',
 '我 没 觉得 不 好看 阿 ～',
 '各种 好看 。 《 追 》 。',
 '没有 侏罗纪 公园 1 好看 ， 不过 比 2 和 3 好看 （ 好像 有点 废话 ）',
 '歌舞 好看 ， 其他 跳过',
 '还 好看',
 '好看 么 ？ 不 觉得',
 '重 看一遍 ， 还是 觉得 好看 。',
 '好看 。',
 '第三部 和 第一部 永远 比 第二部 好看 ！',
 '几个 剧场版 出乎意料 的 好看 啊',
 '非常 的 扯淡 ， 不是 很 好看',
 '你 是 我 见 过 的 … 最最 好看 的   十六岁 少女 …',
 '最近 看 得 比较 好看 的 一部',
 '很 好看 ！',
 '挺 好看 的 ， 演员 的 演技 都 超赞 的',
 '黑泽明 的 电影 有 什么 好看 的',
 '还是 很 好看 的',
 '好看',
 '很 好看',
 '不 好看 。 。 。 动画电影 能 做成 像 千与千寻 的 ， 太少 了 ， 迪士尼 的 电影 都 不 一定 每 一部 好看',
 '很 好看 。',
 '好看',
 '不 好看',
 '明明 挺 好看 的 ， 远高于 预期',
 '你 好看 更好 ， 丑 也 没事',
 '那会 迪亚兹 多 好看 呀',
 '造型 好看',
 '很 好看 ， 精彩',
 '金刚怒目 ！ 装 B 的 电影 才 够 好看 。',
 '不 好看 啊 。 。 。 。 和 焦点访谈 似得 。 。 。',
 '我 觉得 特 好看 呀',
 '好看 啊 . leonardo   dicaprio 好帅 啊 .',
 '圆圆 真 好看',
 '好看 ， 结尾 很 震撼',
 '没有 1 好看',
 '邱淑贞 你 永远 这么 好看',
 '女主角 好 有 个人 魅力 啊 ， 好看',
 '安红饿 想 你 ， 最 好看 的 某 电影',
 '最 好看 的 影片 之一',
 '郑恺 越来越 好看 了 ！',
 '没有 想象 中 的 好看',
 '比一 差远了 ， 虽然 一 也 不 好看',
 '没有 小淘气 不 开心 不 开心 ！ ！ ！ ！ ！ ！ ！ ！ ！ ！ ！ ！ ！ ！ ！ ！ ！ ！ 但 还是 好看 啊 好看 ！ ！ ！ 快银太 可爱   萌死 了',
 '我 倒 是 觉得 挺 好看 了 的',
 '多年 

In [ ]:
for label in lables_with_comment:
    print('lable : {}'.format(label))
    for comment in lables_with_comment[label]:
        print('\t: {}'.format(comment))

## Softmax

In [95]:
vector = np.random.random((1, 100))
vector_2 

In [97]:
vector.shape

(1, 100)

In [99]:
hidden = np.random.random((100, 10000))

In [127]:
result = np.dot(vector, hidden)

In [130]:
def softmax(logits):
    logits = logits - np.max(logits) # normalization
    with_exp = np.exp(logits)
    return with_exp / np.sum(with_exp)

In [141]:
np.array([-111111, 2, 3000000]) / (-111111 + 2 + 3000000)

array([-3.84614719e-02,  6.92307186e-07,  1.03846078e+00])

In [144]:
softmax([3000000, 3000001, 3000003])

array([0.04201007, 0.1141952 , 0.84379473])

In [146]:
np.array([3000000, 3000001, 3000003]) / sum([3000000, 3000001, 3000003])

array([0.33333319, 0.3333333 , 0.33333352])

In [143]:
softmax([-111111, 2, 3000000])

array([0., 0., 1.])

In [129]:
softmax(result)[0]

array([2.47654324e-04, 1.26863337e-05, 1.15141214e-04, ...,
       8.01776206e-06, 9.80738859e-05, 1.82781624e-05])