In [1]:
import tensorflow as tf

In [2]:
a = tf.Variable(initial_value=tf.random_normal(shape=[2, 2]))

In [3]:
b = tf.Variable(initial_value=tf.random_normal(shape=[3, 2]))

In [7]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32_ref>

In [8]:
b

<tf.Variable 'Variable_1:0' shape=(3, 2) dtype=float32_ref>

In [5]:
m = tf.matmul(a, tf.transpose(b))

In [6]:
m

<tf.Tensor 'MatMul_1:0' shape=(2, 3) dtype=float32>

In [17]:
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    a_val, b_val = sess.run([a, b])
    m_val = sess.run(m)

In [18]:
print(a_val)

[[ 0.88622475  0.53196609]
 [-2.00336289  1.43820441]]


In [19]:
print(b_val)

[[-0.20688511  1.49315178]
 [-0.89506471 -1.48872709]
 [ 2.45446134  0.62015283]]


In [20]:
print(m_val)

[[ 0.61095941 -1.58518076  2.50510454]
 [ 2.56192327 -0.34795451 -4.02526999]]
